version: '3'

services:
  db:
    image: mariadb:10.5
    container_name: cnet_db
    environment:
      MYSQL_ROOT_PASSWORD: vFt5SH9YQbPQ
      MYSQL_DATABASE: cnet_wp
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    volumes:
     - db_data:/var/lib/mysql
  wordpress:
    image: wordpress:5.6-php7.4-apache
    container_name: cnet_wordpress
    depends_on:
      - db
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: cnet_wp
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
    ports:
      - "8080:80"

volumes:
  db_data:
