policies:
  - container:
      name: "ping_test"
    communications:
      - processes:
          - path: "/usr/bin/ping"
        sockets:
          - protocol: "icmpv4"
            remote_ip: 10.1.3.10
